### PR TITLE
212 tree for scopes

### LINKED ISSUE #210: Save log configuration in file
**Description:**
Implement saving log configuration information in the file.

### LINKED ISSUE #212: Tree for scopes
**Describe**
In order to implement saving scopes in the config file, as well activating / deactivating scopes in real-time, there is a need to implement scope tree, where the scopes know the child nodes and leaves. So that it should be possible to filter to select scope groups or single scopes to save.

**Solution**
Implement the scope three where each node knows the child nodes and the leafs.
Each node should have a flag indicating active and inactive state, so that it should be possible to group them and save in the config file.

### LINKED ISSUE #216: Assertion failed: ("Buffer too small", 0) [critical]
**Describe the bug**
When logging starts get a crash with assertion:
```txt
minkernel\crts\ucrt\src\appcrt\stdio\output.cpp(282) : Assertion failed: ("Buffer too small", 0)
```

**To Reproduce**
The easiest way to reproduce is to run `LogScopeTest` where it creates the log files.

**Expected behavior**
The system must be stable without crash.

**Desktop or embedded (please complete the following information):**
- OS: Windows 11
- Hardware AMD64
- Compiler MSVC
- AREG SDK version: 1.5.0

### PR DESCRIPTION
**Pull request by vukihub**
Implemented the node tree, save log configuration in the file, fixed couple of raised bugs.

### CODE REVIEW

File: framework/areg/base/private/FileBase.cpp [hunk 1]
```diff
@@ -104,7 +104,7 @@ inline int _readLine(const FileBase & file, ClassType & outValue)
             length = readLength;
             if ( readLength != 0 )
             {
-                readLength = NEString::removeChar<CharType>(static_cast<CharType>('\r'), buffer, static_cast<NEString::CharCount>(readLength), true);
+                // readLength = NEString::removeChar<CharType>(static_cast<CharType>('\r'), buffer, static_cast<NEString::CharCount>(readLength), true);
```
Comment (aregtech) [inline framework/areg/base/private/FileBase.cpp]: Remove comment

File: framework/areg/trace/GETrace.h [hunk 2]
```diff
@@ -67,6 +67,37 @@
...
+    #define PRIO_WARNING        (static_cast<unsigned int>(NETrace::eLogPriority::PrioWarning)  | static_cast<unsigned int>(NETrace::eLogPriority::PrioScope))
+
+    //!< Priority to log error and fatal
+    #define PRIO_ERROR          (static_cast<unsigned int>(NETrace::eLogPriority::PrioError)    | static_cast<unsigned int>(NETrace::eLogPriority::PrioScope))
+
+    //!< Priority to log only fatal
+    #define PRIO_FATAL          (static_cast<unsigned int>(NETrace::eLogPriority::PrioFatal)    | static_cast<unsigned int>(NETrace::eLogPriority::PrioScope))
+
+    //!< Unset logging scopes in priorities
+    #define PRIO_NOSCOPES(x)    ((x)& (~static_cast<unsigned int>(NETrace::eLogPriority::PrioScope)))
```
Comment (aregtech) [inline framework/areg/trace/GETrace.h]: Add a space here `((x)& (`

File: framework/areg/trace/GETrace.h [hunk 3]
```diff
@@ -67,6 +67,37 @@
...
+
+    //!< No logging
+    #define PRIO_NOLOGS         (static_cast<unsigned int>(NETrace::eLogPriority::PrioNotset))
+
+    /**
+     * \brief   Change scope log priority during runtime.
+     *          Pass scope set in DEF_TRACE_SCOPE and priority value with OR operation specified in NETrace::eLogPriority.
+     **/
+    #define SCOPE_PRIORITY_CHANGE(scope, prio)          NETrace::scopePriorityChange(#scope, static_cast<unsigned int>(prio))
```
Comment (aregtech) [inline framework/areg/trace/GETrace.h]: add a macro to get a priority

File: framework/areg/trace/GETrace.h [hunk 4]
```diff
@@ -182,15 +218,51 @@
...
     /**
      * \brief   If !AREG_LOGS, returns true, makes no effect
      **/
     #define IS_TRACE_STARTED()                          ((3-2) > 0)
 
+    /**
+     * \brief   Returns true if logging is enabled
+     **/
+    #define IS_LOG_ENABLED()                            ((3-2) > 0)
+
```
Comment (aregtech) [inline framework/areg/trace/GETrace.h:274]: Format in line 322 and 326

File: framework/areg/trace/NETrace.hpp [hunk 5]
```diff
@@ -86,6 +118,8 @@ namespace NETrace
      **/
     AREG_API NETrace::eLogPriority convFromString( const String& strPrio );
 
+    AREG_API String makePrioString( unsigned int priorities );
```
Comment (aregtech) [inline framework/areg/trace/NETrace.hpp:126]: Document the method

File: framework/areg/trace/NETrace.hpp [hunk 6]
```diff
@@ -914,16 +989,45 @@ inline const char* NETrace::getString(NETrace::eLogPriority prio)
...
         return "NETrace::PrioScope";
+    case NETrace::eLogPriority::PrioValidLogs:
+        return "NETrace::PrioValidLogs";
     case NETrace::eLogPriority::PrioIgnore:
         return "NETrace::PrioIgnore";
     case NETrace::eLogPriority::PrioIgnoreLayout:
         return "NETrace::PrioIgnoreLayout";
     case NETrace::eLogPriority::PrioAny:
         return "NETrace::PrioAny";
+    case NETrace::eLogPriority::PrioValid:
```
Comment (aregtech) [inline framework/areg/trace/NETrace.hpp:1013]: not all enums are present. check again

File: framework/areg/trace/private/LogConfiguration.cpp [hunk 7]
```diff
@@ -93,68 +94,121 @@ bool LogConfiguration::loadConfig( FileBase & file )
...
             }
-        }
 
-        file.moveToBegin( );
-        for ( unsigned int i = 0; i < properties.getSize( ); ++ i )
-        {
-            file.writeString( properties[ i ].makeString( ) );
+            newProperty.clearProperty( );
         }
+    }
```
Comment (aregtech) [inline framework/areg/trace/private/LogConfiguration.cpp:183]: At the end, check if `newProperty` has any data (can be invalid), add to the list.

File: framework/areg/trace/private/NETrace.cpp [hunk 8]
```diff
@@ -172,7 +176,45 @@ AREG_API_IMPL NETrace::eLogPriority NETrace::convFromString( const String& strPr
             return NETrace::eLogPriority::PrioFatal;
     }
 
-    return NETrace::eLogPriority::PrioNotset;
+    return NETrace::eLogPriority::PrioInvalid;
+}
+
+AREG_API_IMPL String NETrace::makePrioString( unsigned int priorities )
+{
+    String result;
```
Comment (aregtech) [inline framework/areg/trace/private/NETrace.cpp:184]: Enable conversion if `AREG_LOGS` is set.

File: framework/areg/trace/private/ScopeNodeBase.cpp [hunk 9]
```diff
@@ -0,0 +1,284 @@
...
+        return true;
+    }
+    else if ( mNodeType == other.mNodeType )
+    {
+        return (mNodeName > other.mNodeName);
+    }
+    else
+    {
+        return false;
+    }
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodeBase.cpp]: Optimize
```cpp
return (mNodeType == other.mNodeType ? (mNodeName > other.mNodeName) : (mNodeType > other.mNodeType);
```

File: framework/areg/trace/private/ScopeNodeBase.cpp [hunk 10]
```diff
@@ -0,0 +1,284 @@
...
+    else if ( mNodeType == other.mNodeType )
+    {
+        return (mNodeName < other.mNodeName);
+    }
+    else
+    {
+        return true;
+    }
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodeBase.cpp]: Optimize
```cpp
return (mNodeType == other.mNodeType ? (mNodeName < other.mNodeName) : (mNodeType < other.mNodeType);
```

File: framework/areg/trace/private/ScopeNodeBase.hpp [hunk 11]
```diff
@@ -0,0 +1,481 @@
...
+          Invalid   = 0 // The node is invalid,             bits: 0000 0000
+        , Leaf      = 2 // The node is root, has no parent, bits: 0000 0010
+        , Node      = 4 // The node that has children,      bits: 0000 0100
+        , Root      = 12// The node does not have children, bits: 0000 1100
+    };
+
+    /**
+     * \brief   The grouping flags to set bitwise.
+     **/
+    enum class eGroupping
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodeBase.hpp]:
```cpp
enum class eGroupping : unsigned char
```

File: framework/areg/trace/private/ScopeNodes.cpp [hunk 12]
```diff
@@ -0,0 +1,429 @@
...
+}
+
+std::pair<ScopeNodeBase &, bool>  ScopeNode::addChildNode( const ScopeNodeBase & child )
+{
+    ScopeNodeBase * scope = &(ScopeNodeBase::invalidNode());
+    bool newEntry{ false };
+
+    if ( child.isLeaf( ) )
+    {
+        std::pair<LeafList::LISTPOS, bool> atPos = mChildLeafs.addIfUnique( ScopeLeaf( child ), false );
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodes.cpp]: `std::pair<LeafList::LISTPOS, bool>` can be `auto`, internal variable

File: framework/areg/trace/private/ScopeNodes.cpp [hunk 13]
```diff
@@ -0,0 +1,429 @@
...
+        scope = &(mChildLeafs.valueAtPosition( atPos.first ));
+        newEntry = atPos.second;
+    }
+    else if (child.isNode( ))
+    {
+        std::pair<NodeList::LISTPOS, bool> atPos = mChildNodes.addIfUnique( ScopeNode( child ), false );
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodes.cpp]: `std::pair<LeafList::LISTPOS, bool>` can be `auto`, internal variable

File: framework/areg/trace/private/ScopeNodes.cpp [hunk 14]
```diff
@@ -0,0 +1,429 @@
...
+}
+
+String ScopeRoot::makeScopePath( const String & /*prefix*/ ) const
+{
+    String result{ NELogConfig::SYNTAX_CMD_LOG_SCOPE };
+    result += NELogConfig::SYNTAX_OBJECT_SEPARATOR;
+    result += Process::getInstance( ).getAppName( );
+    result += NELogConfig::SYNTAX_OBJECT_SEPARATOR;
+
+    return result;
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodes.cpp]:
```cpp
String result;
return result.format("%s.%s.", NELogConfig::SYNTAX_CMD_LOG_SCOPE.data(), Process::getInstance( ).getAppName( ).getString());
```

File: framework/areg/trace/private/ScopeNodes.cpp [hunk 15]
```diff
@@ -0,0 +1,429 @@
...
+}
+
+String ScopeRoot::makeConfigString( const String & parent ) const
+{
+    String prio{ makePrioString( ) };
+    constexpr int size{ 512 };
+    char buffer[ size ];
+    String::formatString( buffer, size, "%s* = %s", parent.getString(), prio.getString() );
+
+    return String( buffer );
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodes.cpp]:
```cpp
String result;
return result.format("%s* = %s"), parent.getString(), makePrioString( ).getString());
```

File: framework/areg/trace/private/ScopeNodes.hpp [hunk 16]
```diff
@@ -0,0 +1,376 @@
...
+     *          It loops all child nodes and removes all entries that match
+     *          the priority.
+     * \return  Returns the number of nodes that are removed.
+     **/
+    virtual unsigned int removePriorityNodesRecursive( unsigned int prioRemove ) override;
+
+    /**
+     * \brief   Returns true if a node has no children nodes.
+     **/
+    virtual bool isEmpty( void ) const;
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodes.hpp]: `override` at the end

File: framework/areg/trace/private/ScopeNodes.hpp [hunk 17]
```diff
@@ -0,0 +1,376 @@
...
+     *              configuration setting and saves in file. Otherwise, it generates scope path and
+     *              calls the method of child entries.
+     *          -   If the entry is the root and has no child entries, it generates application
+     *              scope group entry and sets a configuration for entire application.
+     * \param   file        The file object to write the generated configuration. The file should
+     *                      be already opened for writing.
+     * \param   parentPath  The path name of the parent node. The nodes contain '_' at the end.
+     * \return  Returns the number of nodes that have been saved.
+     **/
+    virtual unsigned int saveNodeConfig( FileBase & file, const String & parentPath ) const;
```
Comment (aregtech) [inline framework/areg/trace/private/ScopeNodes.hpp]: `override` at the end

File: framework/areg/trace/private/TraceProperty.cpp [hunk 18]
```diff
@@ -108,17 +108,27 @@ void TraceProperty::clearProperty( bool clearComment /* = true */ )
...
-String TraceProperty::makeString( void ) const
+String TraceProperty::makeConfigString( void ) const
 {
-    String result(mComment);
-    result += NELogConfig::SYNTAX_LINEEND;
-    result += mProperty.mValue.first.getKey( );
-    result += NELogConfig::SYNTAX_EQUAL;
-    result += static_cast<String>(mProperty.mValue.second);
-    result += NELogConfig::SYNTAX_LINEEND;
+    String result;
```
Comment (aregtech) [inline framework/areg/trace/private/TraceProperty.cpp]: `String result(mComment)` at least the comment should be there.

File: framework/areg/trace/private/TraceProperty.cpp [hunk 19]
```diff
@@ -108,17 +108,27 @@ void TraceProperty::clearProperty( bool clearComment /* = true */ )
...
+    if ( mProperty.mValue.first.isValidKey( ) )
+    {
+        if ( mComment.isEmpty( ) == false )
+        {
+            result += mComment;
+        }
+
+        constexpr int size{ 512 };
+        char buffer[ size ];
+        String::formatString( buffer, size, "%s = %s\n", mProperty.mValue.first.getKey( ).getString( ), static_cast<const char *>(mProperty.mValue.second) );
```
Comment (aregtech) [inline framework/areg/trace/private/TraceProperty.cpp]:
```cpp
String config;
result += config.format("%s = %s", mProperty.mValue.first.getKey( ).getString( ), static_cast<const char *>(mProperty.mValue.second));
```

File: framework/areg/trace/private/TracePropertyKey.cpp [hunk 20]
```diff
@@ -106,21 +106,23 @@ void TracePropertyKey::setKey(const String & fullKey)
...
 
-        mConfigKey  = mModuleName.isEmpty() ? NELogConfig::eConfigKey::KeyGlobal : NELogConfig::eConfigKey::KeyLocal;
+        if ( mModuleName.isEmpty( ) || (mModuleName == NELogConfig::SYNTAX_SCOPE_GROUP) )
+        {
+            mConfigKey  = NELogConfig::eConfigKey::KeyGlobal;
+        }
+        else
+        {
+            mConfigKey = NELogConfig::eConfigKey::KeyLocal;
+        }
```
Comment (aregtech) [inline framework/areg/trace/private/TracePropertyKey.cpp]:
```cpp
mConfigKey = (mModuleName.isEmpty( ) || (mModuleName == NELogConfig::SYNTAX_SCOPE_GROUP)) ? NELogConfig::eConfigKey::KeyGlobal : NELogConfig::eConfigKey::KeyLocal;
```

File: tests/units/LogScopesTest.cpp [hunk 21]
```diff
@@ -0,0 +1,390 @@
...
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_errLeaf2 );
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_fatalNode1_leaf );
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_fatalNode2_leaf );
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_warnNode1_leaf );
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_warnNode2_leaf );
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_infoNode1_noScope );
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_infoNode2_noScope );
+DEF_TRACE_SCOPE( areg_unit_tests_LogScopeTest_ScopePriorityGroupping_information );
+TEST( LogScopeTest, ScopePriorityGroupping )
+{
```
Comment (aregtech) [inline tests/units/LogScopesTest.cpp:251]: In this test would be good to save the scope priority and later compare the values when load config file.

**Review by aregtech — CHANGES_REQUESTED** [review]
Please see the comments.

File: framework/areg/trace/private/LogConfiguration.cpp [hunk 22]
```diff
@@ -93,68 +94,121 @@ bool LogConfiguration::loadConfig( FileBase & file )
...
     return saveConfig( mFilePath );
 }
 
 bool LogConfiguration::saveConfig( const String & filePath ) const
 {
-    String path = filePath.isEmpty( ) ? _getDefaultConfigFile( ) : filePath;
-    path = File::getFileFullPath( File::normalizePath( path ) );
-    File fileConfig( path, FileBase::FO_MODE_EXIST | FileBase::FO_MODE_READ | FileBase::FO_MODE_TEXT | FileBase::FO_MODE_SHARE_READ );
-    fileConfig.open( );
+    constexpr unsigned int mode{ FileBase::FO_MODE_WRITE | FileBase::FO_MODE_TEXT | FileBase::FO_MODE_CREATE | FileBase::FO_MODE_SHARE_READ | FileBase::FO_MODE_SHARE_WRITE };
```
Comment (aregtech) [inline framework/areg/trace/private/LogConfiguration.cpp]: The `FileBase::FO_MODE_SHARE_WRITE` can be removed. We don't want to share

File: framework/areg/trace/private/LogConfiguration.cpp [hunk 23]
```diff
@@ -93,68 +94,121 @@ bool LogConfiguration::loadConfig( FileBase & file )
...
+    constexpr unsigned int mode{ FileBase::FO_MODE_EXIST | FileBase::FO_MODE_READ | FileBase::FO_MODE_TEXT | FileBase::FO_MODE_SHARE_READ };
+    File fileConfig( mFilePath, mode);
 
-    if ( file.isOpened( ) && file.canWrite( ) )
+    if ( fileConfig.open( ) == false )
     {
-        file.moveToBegin( );
-        PropertyList properties( mProperties );
-        PropertyList scopes;
+        ASSERT( false );
```
Comment (aregtech) [inline framework/areg/trace/private/LogConfiguration.cpp]: remove assert

File: framework/areg/trace/private/LogConfiguration.cpp [hunk 24]
```diff
@@ -93,68 +94,121 @@ bool LogConfiguration::loadConfig( FileBase & file )
...
+        return false;
+    }
 
-        const String & moduleName = Process::getInstance( ).getAppName( );
-        String line;
-        TraceProperty newProperty;
-        while ( file.readLine( line ) > 0 )
+    if ( file.isOpened( ) == false )
+    {
+        ASSERT( false );
```
Comment (aregtech) [inline framework/areg/trace/private/LogConfiguration.cpp]: remove assert

File: framework/areg/trace/private/LogConfiguration.cpp [hunk 25]
```diff
@@ -93,68 +94,121 @@ bool LogConfiguration::loadConfig( FileBase & file )
...
+        return false;
+    }
+
+    if ( file.canWrite( ) == false )
+    {
+        ASSERT( false );
```
Comment (aregtech) [inline framework/areg/trace/private/LogConfiguration.cpp]: remove assert

File: framework/areg/trace/private/LogConfiguration.cpp [hunk 26]
```diff
@@ -93,68 +94,121 @@ bool LogConfiguration::loadConfig( FileBase & file )
...
-    path = File::getFileFullPath( File::normalizePath( path ) );
-    File fileConfig( path, FileBase::FO_MODE_EXIST | FileBase::FO_MODE_READ | FileBase::FO_MODE_TEXT | FileBase::FO_MODE_SHARE_READ );
-    fileConfig.open( );
+    constexpr unsigned int mode{ FileBase::FO_MODE_WRITE | FileBase::FO_MODE_TEXT | FileBase::FO_MODE_CREATE | FileBase::FO_MODE_SHARE_READ | FileBase::FO_MODE_SHARE_WRITE };
+
+    String path = filePath.isEmpty( ) ? mFilePath : filePath;
+    // path = File::getFileFullPath( File::normalizePath( path ) );
+    File fileConfig( path, mode );
+    
+    VERIFY(fileConfig.open( ));
```
Comment (aregtech) [inline framework/areg/trace/private/LogConfiguration.cpp]: Not sure whether we need `VERIFY`

**Review by aregtech — CHANGES_REQUESTED** [review]
Added more comments

**Review by aregtech — APPROVED** [review]
looks good
